version: 2
jobs:
  build:
    docker:
      - image: circleci/node:dubnium-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ .Environment.CACHE_VERSION }}
            - dependencies-
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: test to see if there are the env var
          command: echo "env var  " && echo $NETLIFY_AUTH_TOKEN
      - run:
          name: Print the Current Time
          command: date
      - run :
          name: yarn install cmd
          command: yarn install
      - run:
          name: Deploy app
          command: npx netlify-cli deploy --prod --auth $NETLIFY_AUTH_TOKEN --site $NETLIFY_SITE_ID
      - save_cache:
          paths:
            - ./cache-folder
          key: v1-dependencies-{{ .Environment.CACHE_VERSION }}


  test:
    docker:
      - image: debian:stretch
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ .Environment.CACHE_VERSION }}
            # fallback to using the latest cache if no exact match is found
            - dependencies-
  buildforprod:
    docker:
      - image: debian:stretch
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ .Environment.CACHE_VERSION }}
            # fallback to using the latest cache if no exact match is found
            - dependencies-
      - run:
          comand: yarn build

workflows:
  version: 2
  build-general:
    jobs:
      - build
      # - build:
      #     requires:
      #       - install
      # - apply-db-schema:
      #     requires:
      #       - install

      - test:
          requires:
            - build
      - buildforprod:
          requires:
            - build
            - test