version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.

      - run:
          name: Print the Current Time
          command: date

      - run :
        command: yarn install

      - save_cache:
          paths:
            - ./cache-folder
          key: v1-dependencies-{{ .Environment.CACHE_VERSION }}


  test:
    docker:
      - image: debian:stretch
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ .Environment.CACHE_VERSION }}
            # fallback to using the latest cache if no exact match is found
            - dependencies-
  buildforprod:
    docker:
      - image: debian:stretch
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ .Environment.CACHE_VERSION }}
            # fallback to using the latest cache if no exact match is found
            - dependencies-
      - run:
          comand: yarn build

workflows:
  version: 2
  build-general:
    jobs:
      - build
      # - build:
      #     requires:
      #       - install
      # - apply-db-schema:
      #     requires:
      #       - install
      - test:
          requires:
            - install
      - buildforprod:
          requires:
            - install
            - test